[project]
name = "wolfi-jupyter"
version = "0.1.0"
description = "Add a short description here"
authors = ["vera <veronika.m.winters@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
