[project]
name = "wolfi-jupyter"
version = "0.1.0"
description = "Add a short description here"
authors = ["vera <veronika.m.winters@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.10"
bokeh = ">=3.3.4,<3.4"
ipywidgets = ">=8.1.1,<8.2"
h5py = ">=3.10.0,<3.11"
cython = ">=3.0.7,<3.1"
ipympl = ">=0.9.3,<0.10"
patsy = ">=0.5.6,<0.6"
statsmodels = ">=0.14.1,<0.15"
cloudpickle = ">=3.0.0,<3.1"
numpy = ">=1.26.3,<1.27"
sqlalchemy = ">=2.0.25,<2.1"
scikit-learn = ">=1.4.0,<1.5"
numba = ">=0.58.1,<0.59"
sympy = ">=1.12,<2"
dill = ">=0.3.7,<0.4"
seaborn = ">=0.13.1,<0.14"
altair = ">=5.2.0,<5.3"
xlrd = ">=2.0.1,<2.1"
widgetsnbextension = ">=4.0.9,<4.1"
nbclassic = ">=1.0.0,<1.1"
beautifulsoup4 = ">=4.12.3,<4.13"
scipy = ">=1.12.0,<1.13"
scikit-image = ">=0.22.0,<0.23"
dask = ">=2024.1.0,<2024.2"
protobuf = ">=4.24.4,<4.25"
pandas = ">=2.2.0,<2.3"
matplotlib = ">=3.8.2,<3.9"
numexpr = ">=2.8.8,<2.9"
bottleneck = ">=1.3.7,<1.4"

[pypi-dependencies]
tables = "*"
